model_name: 'ViT'
device: 'cuda:0'
batch_size: 16


training:
  lr: 0.0001
  step: 10
  gamma: 0.1
  epochs: 50
  momentum: 0.9
  decay: 0.0005

ViT-model:
  ViTconfig: "ViT-B_16"
  pretrained: "checkpoints/ViT-B_16.npz"
  vis: False
  fine_tune: False
  n_patches: 1
  Decoder:
    multiScale: True
    base_grid: 16
    num_features: 768
    decoder_width: 1.0

ResNet-model:0
  version: 101
  pretrained: True
  fine_tune: False
  Decoder:
    base_grid: 16
    num_features: 1024
    decoder_width: 0.75
 
dataset:
  path: 'dataset/nyu_data.zip'
  n_used_data: 20000
  n_test_data: 1000
  test_path: 'dataset/nyu_test.zip'
  input_shape: (224, 224, 3)
  channel_swap: 0.5
  num_workers: 20