model_name: 'ViT-depth estimation'
device: 'cuda:0'
batch_size: 32


training:
  lr: 0.0001
  epochs: 1

ViT-model:
  ViTconfig: "ViT-B_16"
  pretrained: "checkpoints/ViT-B_16.npz"
  vis: False
  fine_tune: True
  n_patches: 1
  Decoder:
    num_features: 768
    decoder_width: 1.0

 
dataset:
  path: 'dataset/nyu_data.zip'
  n_used_data: 20000
  test_path: 'dataset/nyu_test.zip'
  input_shape: (224, 224, 3)
  channel_swap: 0.5
  num_workers: 20